---
nodes:
- id: "@START"
  type: "terminal"
  text: "Начало"
  x: 543
  "y": 52
  width: 54
  height: 43
  dialog:
    message_timeout: 120
    commands:
    - answer:
      - "Запиши"
      - "Запись"
      - "Напомни"
      - "Зарегистрируй"
      - "Назначь"
      - "Оформи"
      node_to: "@start"
- id: "@END"
  type: "terminal"
  text: "Конец"
  success_ending: true
  x: 352
  "y": 735
  width: 61
  height: 59
- id: "@start"
  type: "decision"
  message_timeout: 240
  contact_type: "message"
  title: "Пригласить пациентов на диспансерное наблюдение"
  text: "%name%, здравствуйте! Напоминаем, подходит время очередного наблюдения. \n\
    \      Подскажите, готовы ли Вы записаться? %[Да, Нет]%  "
  options:
  - answer:
    - "да"
    - "yes"
    - "согласен"
    - "угу"
    node_to: "@reg_contact_yes"
  - answer:
    - "нет"
    - "no"
    - "не согласен"
    - "неа"
    node_to: "@stop"
  x: 338
  "y": 120
  width: 100
  height: 100
- id: "@reg_contact_yes"
  type: "process"
  contact_type: "message"
  title: "Связаться с пациентом для записи на приём"
  text: "Для записи наберите номер телефона 111-11-11. Будем вас ждать. До свидани\
    я!"
  x: 186
  "y": 461
  width: 79
  height: 30
  node_to: "@END"
- id: "@stop"
  type: "decision"
  contact_type: "message"
  title: "Закончить переписку с сожалением"
  text: "Очень жаль :( Своевременное наблюдение поможет снизить риски развития заб\
    олевания. \n      Если Вы все же готовы записаться, то выберите %[Записаться,\
    \ Пока не пойду]%"
  options:
  - answer:
    - "Пока не пойду"
    - "нет"
    - "no"
    - "не согласен"
    - "неа"
    node_to: "@request_reason"
  - answer:
    - "Записаться"
    node_to: "@reg_contact_yes"
  x: 471
  "y": 304
  width: 100
  height: 100
- id: "@request_reason"
  type: "process"
  contact_type: "message"
  title: "Запросить причину"
  text: "По какой причине вы отказываетесь от явки?"
  x: 467
  "y": 492
  width: 127
  height: 60
  node_to: "@take_reason"
- id: "@take_reason"
  type: "process"
  contact_type: "message"
  title: "Принять причину"
  text: "Ваш ответ принят: %PREVIOUS_MSG%. Спасибо. До свидания!"
  x: 480
  "y": 609
  width: 81
  height: 30
  node_to: "@END"
connections:
- sourceId: "@reg_contact_yes"
  targetId: "@END"
  sourceAnchor: "Bottom"
  targetAnchor: "Top"
- sourceId: "@take_reason"
  targetId: "@END"
  sourceAnchor: "Bottom"
  targetAnchor: "Top"
- sourceId: "@stop"
  targetId: "@request_reason"
  sourceAnchor: "Bottom"
  targetAnchor: "Top"
- sourceId: "@stop"
  targetId: "@reg_contact_yes"
  sourceAnchor: "Bottom"
  targetAnchor: "Top"
- sourceId: "@START"
  targetId: "@start"
  sourceAnchor: "Bottom"
  targetAnchor: "Top"
- sourceId: "@start"
  targetId: "@reg_contact_yes"
  sourceAnchor: "Bottom"
  targetAnchor: "Top"
- sourceId: "@start"
  targetId: "@stop"
  sourceAnchor: "Bottom"
  targetAnchor: "Top"
- sourceId: "@request_reason"
  targetId: "@take_reason"
  sourceAnchor: "Bottom"
  targetAnchor: "Top"
